baseURL = 'https://richkuz.net/'
languageCode = 'en-us'
title = 'RichKuz Blog'

theme = 'PaperMod'

# config.toml
[params]
  disablePWA = true # Optional, but often helpful
  
[services]
  [services.googleAnalytics]
    disable = true

